name: Cron job to delete ended Jobs

on:
  workflow_dispatch:
  schedule: # "At 06:00 PM, only on Monday"
    - cron: "0 18 * * 1"

jobs:
  deleteJobs:
    runs-on: ubuntu-latest
    steps:
      - name: Call the delete api
        uses: Satak/webrequest-action@v1.2.3
        with:
          # Web request URL endpoint
          url: "https://juniorjobs.pages.dev/api/cleanJobs"
          method: POST
          headers: '{"auth": "${{ secrets.DEL_TOKEN }}"}'
          
